### PR TITLE
First attempt to resolving the github pull request issues

### PR DESCRIPTION
**Pull request by abhitsahota**
Due to issues on previous pull requests on GitHub tests not passing. I have ran eslint fix, updated the ignore file in an attempt to pass the GitHub tests. 

Some other formatting changes may appear appended to my request due to updates made on prettier and it's applications to new file directories. I can make that into a separate commit or PR if needed. 

Attached ticket here: https://trello.com/b/lmGzARca/labspt17-cityspire-c

### CODE REVIEW

**Comment by abhitsahota** [comment]
So, on submission I've seen that all the checks have passed. Let me know if you have any questions.

**Comment by abhitsahota** [comment]
[Fixed the backend tests for GitHub to let other PRs pass](https://trello.com/c/NMPDxQBI/63-fixed-the-backend-tests-for-github-to-let-other-prs-pass)

**Comment by JasonNeale** [comment]
It looks good. I'm glad you found the issue.
The only thing I notice was a type in your comment for PR in the first sentence:

"Due to issues on previous pull requests on gut hub tests not passing."

should be

"Due to issues on previous pull requests on GitHub tests not passing."

The actual PR looks good. I'm glad you caught the first line in the migrations file from the legacy code that needed to be commented out.

**Review by JasonNeale — APPROVED** [review]
It looks good. I'm glad you found the issue.
The only thing I notice was a type in your comment for PR in the first sentence:

"Due to issues on previous pull requests on gut hub tests not passing."

should be

"Due to issues on previous pull requests on GitHub tests not passing."

The actual PR looks good. I'm glad you caught the first line in the migrations file from the legacy code that needed to be commented out.

**Comment by abhitsahota** [comment]
Thanks Jason - updated the submission to reflect your comments.

**Review by codyt11 — APPROVED** [review]
Everything is looking great, thanks for cleaning up my old code! If you have any questions feel free to reach out!

**Review by jhoyt200931 — APPROVED** [review]

**Pull request merged**
